# travis config file for a2docs
#
# travis-first-try: get django loaded, and test as "true"
#
# Tell Travis you want a Python environment to test in
language: python
sudo: false
# List the versions of Python you'd like to test against
# Taking out Python 2.5 because it's apparently not installable
# The latest Django wants to be on the latest Python 3
python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
# List the versions of Django you'd like to test against
# We probably need earlier versions too, since the project
# was originally built on Django 1.2.3
env:
 - DJANGO_VERSION=1.2.3
 - DJANGO_VERSION=1.7.9
 - DJANGO_VERSION=1.8.3
matrix:
  exclude:
    - python: "2.5"
      env: "DJANGO_VERSION=1.8.3"
# Tell it the things it will need to install when it boots
install:
   # Install whatever version of Django that's listed above
   # Travis is currently working on
   # take the explicit Django version out of requrirements.txt to make this work
 - pip install Django==$DJANGO_VERSION
 - pip install pyflakes pep8 coverage python-coveralls
 - pip install -r requirements.txt
 - true
# Tell Travis how to run the test script itself
# This should fail until we get some test coverage running
script:
 - python -c "import django; print(django.get_version())"
