# Tell Travis you want a Python environment to test in
language: python
sudo: false
# List the versions of Python you'd like to test against
# Taking out Python 2.5 because it's apparently not installable
python:
 - "2.6"
 - "2.7"
# List the versions of Django you'd like to test against
# We probably need earlier versions too, since the project
# was originally built on Django 1.2-BETA
env:
 - DJANGO_VERSION=1.4.21
 - DJANGO_VERSION=1.7.9
 - DJANGO_VERSION=1.8.3
matrix:
  exclude:
    - python: "2.5"
      env: "DJANGO_VERSION=1.8.3"
# Tell it the things it will need to install when it boots
install:
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION
 - pip install pyflakes pep8 coverage python-coveralls
 - python setup.py install
# Tell Travis how to run the test script itself
# This should fail until we get some test coverage running
script:
 - pep8 softhyphen
 - pyflakes softhyphen
 - coverage run setup.py test
